// Code generated by "stringer -type=Action"; DO NOT EDIT

package main

import "fmt"

const _Action_name = "STOPPEDPENDINGUPUPRIGHTRIGHTDOWNRIGHTDOWNDOWNLEFTLEFTUPLEFTFALLINGJUMPJUMPRIGHTJUMPUPJUMPLEFT"

var _Action_index = [...]uint8{0, 7, 14, 16, 23, 28, 37, 41, 49, 53, 59, 66, 70, 79, 85, 93}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return fmt.Sprintf("Action(%d)", i)
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
