// Code generated by "stringer -type=Action"; DO NOT EDIT

package main

import "fmt"

const _Action_name = "STOPPEDUPUPRIGHTRIGHTDOWNRIGHTDOWNDOWNLEFTLEFTUPLEFTFALLINGJUMPJUMPRIGHTJUMPUPJUMPLEFT"

var _Action_index = [...]uint8{0, 7, 9, 16, 21, 30, 34, 42, 46, 52, 59, 63, 72, 78, 86}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return fmt.Sprintf("Action(%d)", i)
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
